### ISSUE TITLE
Unable to grab Netflix account, due to duplicate/error. Index: 1

### ISSUE THREAD

**Issue by giorgarasSOS** [I2rys/opengen-bot#1]
What do i do?
.
.
.

Finished grabbing 1 Netflix accounts.
Saving the results to /home/kali/Desktop/SpotifyAccounts
Unable to grab Netflix account, due to duplicate/error. Index: 1
Retrying...
Finished grabbing 1 Netflix accounts.
Saving the results to /home/kali/Desktop/SpotifyAccounts
Unable to grab Netflix account, due to duplicate/error. Index: 1
Retrying...
Finished grabbing 1 Netflix accounts.
Saving the results to /home/kali/Desktop/SpotifyAccounts
Unable to grab Netflix account, due to duplicate/error. Index: 1
Retrying...
Finished grabbing 1 Netflix accounts.
Saving the results to /home/kali/Desktop/SpotifyAccounts
Unable to grab Netflix account, due to duplicate/error. Index: 1
Retrying...
Exception in PromiseRejectCallback:
/root/opengen-bot/index.js:47
        return Grab(account_type)
                                 

RangeError: Maximum call stack size exceeded
(node:4163) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at console.value.
.
.
.

**Comment by I2rys** [comment]
Hello @giorgarasSOS, please make sure openbot-gen has the permission to write files.

**Comment by giorgarasSOS** [comment]
> Hello @giorgarasSOS, please make sure openbot-gen has the permission to write files.

How do I do that?

**Comment by I2rys** [comment]
> Author

You can give it a permission by running node in sudo or by using chmod. For example:
```
sudo node index.js
```
```
chmod +x index.js
```

**Comment by giorgarasSOS** [comment]
> > Author
> 
> You can give it a permission by running node in sudo or by using chmod. For example:
> ```
> sudo node index.js
> ```
> ```
> chmod +x index.js
> ```

Oooo yes yes thank you so much man

**Comment by I2rys** [comment]
> > > Author
> > 
> > 
> > You can give it a permission by running node in sudo or by using chmod. For example:
> > ```
> > sudo node index.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > chmod +x index.js
> > ```
> 
> Oooo yes yes thank you so much man

If that resolves your problem please close the issue. :D

**Comment by giorgarasSOS** [comment]
> > > > Author
> > > 
> > > 
> > > You can give it a permission by running node in sudo or by using chmod. For example:
> > > ```
> > > sudo node index.js
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > chmod +x index.js
> > > ```
> > 
> > Oooo yes yes thank you so much man
> 
> If that resolves your problem please close the issue. :D

Another thing more of a question really...<output> is where the file is stored right?
