### ISSUE TITLE
your api is trash

### ISSUE THREAD

**Issue by Altify-Development** [I2rys/opengen-bot#12]
its just a psuedo generator dude look i made one too - [windows key gen](https://windows-key-generator.netlify.app/)

**Comment by I2rys** [comment]
Hello @Altify-Development,

I think your misunderstanding, If you look at the issues you will see that It's a third party API and I cannot assist about it's generating. I simply just made a tool for it.

**Comment by Altify-Development** [comment]
well then make an tool for h-gen.xyz, that is something people want.

**Comment by I2rys** [comment]
> well then make an tool for h-gen.xyz, that is something people want.

I already tried but was unable to because of captcha, delay & linkvertise. I also think that this issue has been solved.
