### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ashwanik936** [I2rys/opengen-bot#13]
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'C:\Users\Ashwani\Desktop\GEN\index.js'
←[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:804:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

Node.js v18.6.0

**Comment by I2rys** [comment]
Hello @Ashwanik936, are you sure that there is an index.js file in the **GEN** directory?
