### ISSUE TITLE
Gen

### ISSUE THREAD

**Issue by swooptiyar** [I2rys/opengen-bot#16]

**Comment by I2rys** [comment]
Hello @swooptiyar

**Comment by Hammadzaki71** [comment]
@I2rys  im need help add me on discord xbrbro pro11234#0096

**Comment by I2rys** [comment]
> pro11234#0096

I have added you mate.

**Comment by Hammadzaki71** [comment]
can u give me ur discord again pls

**Comment by I2rys** [comment]
> can u give me ur discord again pls

Sure Hammad. My Discord is **I2rys**.

**Comment by I2rys** [comment]
Due to inactivity of this issue I will be closing it.
