### ISSUE TITLE
Generator not working.

### ISSUE THREAD

**Issue by KaysonIsCoool** [I2rys/opengen-bot#3]
Hi, I have an issue about the generator, is that when I enter the command, (node "C:\Users\name\Documents\GitHub\opengen-bot\index.js" Disney plus 10 "C:\Users\name\Documents\GitHub\opengen-bot\dis.txt")
it just reply me 'amount not a number' even i tried to change the numbers, it wont work, is it just me tying it wrong, or is it a bug?

**Comment by KaysonIsCoool** [comment]
oh never mind! is my problem, there is no need the'plus'!

**Comment by I2rys** [comment]
Hello @KaysonIsCoool, yes the plus is not needed only use **disney** and that should fix your problem. :)
