### ISSUE TITLE
No matter how many accounts I create, why does it say the password is wrong?

### ISSUE THREAD

**Issue by selim1337** [I2rys/opengen-bot#7]
No matter how many accounts I create, why does it say the password is wrong?

**Comment by I2rys** [comment]
> No matter how many accounts I create, why does it say the password is wrong?

Hello, I'm afraid I can't help you with this because I have no control over the website and the code just simply request to the website API to get accounts. Though some services have low valid percentage some services like NordVPN sometimes works a lot.
