### ISSUE TITLE
help  not working

### ISSUE THREAD

**Issue by 1907amk** [I2rys/opengen-bot#8]
found 0 vulnerabilities
thy@penguin:~$ node index.js disney 100 disney+accounts.txt
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/thy/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

u think u can help me with this?

**Comment by I2rys** [comment]
> found 0 vulnerabilities thy@penguin:~$ node index.js disney 100 disney+accounts.txt internal/modules/cjs/loader.js:818 throw err; ^
> 
> Error: Cannot find module '/home/thy/index.js' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15) at Function.Module._load (internal/modules/cjs/loader.js:667:27) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) at internal/main/run_main_module.js:17:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }
> 
> u think u can help me with this?

Hello, yes I can help you with the problem, the problem seems to be the node can't find the index.js in the current directory your using. Are you sure the index.js is in the home directory?

**Comment by 1907amk** [comment]
i am not sure  where can i check that

**Comment by I2rys** [comment]
> i am not sure where can i check that

Hmm since your using Linux type **ls** to see the directories & files in the current directory. Do you not know how to navigate through directories in Linux?

**Comment by 1907amk** [comment]
> 

No i dont know how to do that and yes i use linux

**Comment by I2rys** [comment]
> > 
> 
> No i dont know how to do that and yes i use linux

I see you should probably read https://phoenixnap.com/kb/linux-cd-command
